### PR TITLE
2 bugs, 2 improvements, 1 new feature. Fixes #2

### LINKED ISSUE #2: [IDEA] Resolution independence for other things as well
Some engines like Godot, automatically gives values like mouse and touch position in the range of target game resolution instead of the real screen resolution. Could that be of use for CScreen?

Maybe there can be a function like CScreen.getInTargetCoords(x, y)?

So that I can do something like `local mousepos = CScreen.getInTargetCoords(love.mouse.getPosition())` and not worry about the actual resolution.

If you're interested I can also try to do it and make a PR.

Let me know. Thanks.

### PR DESCRIPTION
**Pull request by tapir**
I think you will find couple of them useful. Pick the ones you like 👍

### CODE REVIEW

**Comment by tapir** [comment]
Oh, I didn't change the min version this time. Is that one really necessary? You save only 1.5 kbytes :D

**Comment by CodeNMore** [comment]
I currently don't have time to test this, funny enough, but at a quick glance doesn't your "Prevent unnecessary set/gets if not centering" commit not scale at all? Even if we aren't centered, I believe we still need to scale, if I'm not mistaken.

**Comment by tapir** [comment]
I might be wrong but from what I understand that part is only for the letterboxes. If you don't want centering, there is no need for letterboxes. No?
I've just tested this code again and even without centering everythign scales correctly thanks to cscreen.apply()

**Comment by CodeNMore** [comment]
Ah, you are correct! Thanks!

**Pull request merged**
